---
title: "writing functions"
output: html_document
date: "2024-11-13"
---
```{r setup, include = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom") )

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.comtinuous.fill = "viridis"
)
```


## Do something Simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec = mean(x_vec)) /sd(x_vec)
```

I want a function to compute z scores
```{r}
z_scores = function(x){
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x_vec)
```

try my function on other things

```{r, error=TRUE}
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multiple outputs

```{r}
mean_and_sd = function(x){
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  

}

```

```{r}
x_vec = rnorm(100, mean = 3, sd = 4)
mean_and_sd(x_vec)
```

##Multiple inputs

```{r}
sim_data = 
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
```

```{r}
sim_mean_sd = function(samp_size, mu, sigma) {
 
   sim_data = 
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
  
}

sim_mean_sd(100, 6, 3)
```

